name: nbvalx CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    if: >-
      (
        (
          github.event_name == 'schedule'
          && github.repository == 'multiphenics/nbvalx'
        ) || (
            github.event_name != 'schedule'
            && !(
              contains(github.event.head_commit.message, '[ci skip]')
              || contains(github.event.head_commit.message, '[skip ci]')
            )
        )
      )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenMPI
        run: |
          sudo apt install libopenmpi-dev
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nbvalx
        run: |
          python3 -m pip install .[docs,lint,tests]
      - name: Run flake8 checks on python files
        run: |
          python3 -m flake8 .
      - name: Run documentation generation
        run: |
          cd docs && make html
      - name: Run unit tests (serial)
        id: run_unit_tests_serial
        run: |
          COVERAGE_FILE=.coverage_unit_serial python3 -m coverage run --source=nbvalx -m pytest -n auto tests/unit
      - name: Run unit tests (parallel)
        id: run_unit_tests_parallel
        run: |
          COVERAGE_FILE=.coverage_unit_parallel mpirun -n 2 python3 -m coverage run --source=nbvalx --parallel-mode -m pytest tests/unit
      - name: Check for stray outputs, counts and metadata in notebooks test files
        uses: RBniCS/check-jupyter-metadata-action@main
        with:
          pattern: "tests/notebooks/data/**/*.ipynb"
      - name: Run notebooks tests (serial, without collapse)
        id: run_notebooks_tests_serial_without_collapse
        run: |
          COVERAGE_FILE=.coverage_notebooks_serial_without_collapse python3 -m coverage run --source=nbvalx -m pytest -n auto --dist loadscope tests/notebooks
      - name: Run notebooks tests (serial, with collapse)
        id: run_notebooks_tests_serial_with_collapse
        run: |
          COVERAGE_FILE=.coverage_notebooks_serial_with_collapse python3 -m coverage run --source=nbvalx -m pytest -n auto --dist loadscope --tag-collapse tests/notebooks
      - name: Run notebooks tests (parallel)
        id: run_notebooks_tests_parallel
        run: |
          COVERAGE_FILE=.coverage_notebooks_parallel python3 -m coverage run --source=nbvalx -m pytest --np 2 tests/notebooks
      - name: Combine coverage reports
        run: |
          coverage combine .coverage*
          coverage report --fail-under=100 --show-missing --skip-covered
      - name: Run flake8 checks on notebooks files, including those automatically generated by pytest
        run: |
          nbqa flake8 .
      - name: Warn if scheduled workflow is about to be disabled
        if: github.repository == 'multiphenics/nbvalx' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci.yml
          days-elapsed: 55
          token: ${{ secrets.SCHEDULED_ACTIONS_WARNING_API_TOKEN }}
